service: get-favourite-films
frameworkVersion: '3'

provider:
  name: aws
  environment:
    HOST: swapi.py4e.com/api/
    PATH: films/
    PK: id
    TABLE: favourite-film
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:sa-east-1:270471814480:table/favourite-film
  runtime: nodejs14.x
  region: sa-east-1

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: favourite/film
          method: get