service: get-films
frameworkVersion: '3'

provider:
  name: aws
  environment:
    HOST: swapi.py4e.com/api/
    PATH: films/
  runtime: nodejs14.x
  region: sa-east-1

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: films
          method: get